### ISSUE TITLE
mmfd lässt sich nicht von procd-init-script starten

### ISSUE THREAD

**Issue by christf** [tcatm/mmfd#1]
in einer interaktiven Konsole startet mmfd, wird es von dem init script aufgerufen mag epoll_ctl nicht "operation not permitted" siehe strace

 cat /etc/init.d/gluon-mmfd  
 #!/bin/sh /etc/rc.common 

 START=50

 USE_PROCD=1
 PROG=/usr/sbin/mmfd

 start_service () {
         procd_open_instance
         procd_set_param stdout 1
         procd_set_param stderr 1
         procd_set_param command /usr/bin/strace "$PROG"
         procd_close_instance
 }
# 

Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: execve("/usr/sbin/mmfd", ["/usr/sbin/mmfd"], [/\* 7 vars _/]) = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|0x4000000, -1, 0) = 0x77a26000
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: stat("/etc/ld.so.cache", 0x7ffd3d80)    = -1 ENOENT (No such file or directory)
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: open("/lib/libsetlbf.so", O_RDONLY)     = 3
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: fstat(3, {st_mode=S_IFREG|0644, st_size=2184, ...}) = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|0x4000000, -1, 0) = 0x77a23000
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: read(3, "\177ELF\1\2\1\0\0\0\0\0\0\0\0\0\0\3\0\10\0\0\0\1\0\0\5@\0\0\0004"..., 4096) = 2184
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: mmap(NULL, 69632, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x779fd000
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: mmap(0x779fd000, 2084, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0x779fd000
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: mmap(0x77a0d000, 2184, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0x77a0d000
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: close(3)                                = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: munmap(0x77a23000, 4096)                = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: open("/lib/libgcc_s.so.1", O_RDONLY)    = 3
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: fstat(3, {st_mode=S_IFREG|0644, st_size=78648, ...}) = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|0x4000000, -1, 0) = 0x77a23000
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: read(3, "\177ELF\1\2\1\0\0\0\0\0\0\0\0\0\0\3\0\10\0\0\0\1\0\0006\340\0\0\0004"..., 4096) = 4096
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: mmap(NULL, 147456, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x779d9000
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: mmap(0x779d9000, 78268, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0x779d9000
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: mmap(0x779fc000, 824, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x13000) = 0x779fc000
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: close(3)                                = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: munmap(0x77a23000, 4096)                = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: open("/lib/libc.so.0", O_RDONLY)        = 3
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: fstat(3, {st_mode=S_IFREG|0755, st_size=359596, ...}) = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|0x4000000, -1, 0) = 0x77a23000
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: read(3, "\177ELF\1\2\1\0\0\0\0\0\0\0\0\0\0\3\0\10\0\0\0\1\0\0\235\0\0\0\0004"..., 4096) = 4096
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: mmap(NULL, 446464, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7796c000
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: mmap(0x7796c000, 352480, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0x7796c000
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: mmap(0x779d2000, 7340, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x56000) = 0x779d2000
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: mmap(0x779d4000, 17508, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x779d4000
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: close(3)                                = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: munmap(0x77a23000, 4096)                = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: open("/lib/libgcc_s.so.1", O_RDONLY)    = 3
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: fstat(3, {st_mode=S_IFREG|0644, st_size=78648, ...}) = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: close(3)                                = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: open("/lib/libc.so.0", O_RDONLY)        = 3
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: fstat(3, {st_mode=S_IFREG|0755, st_size=359596, ...}) = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: close(3)                                = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: open("/lib/libc.so.0", O_RDONLY)        = 3
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: fstat(3, {st_mode=S_IFREG|0755, st_size=359596, ...}) = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: close(3)                                = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: stat("/lib/ld-uClibc.so.0", {st_mode=S_IFREG|0755, st_size=28972, ...}) = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|0x4000000, -1, 0) = 0x77a23000
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: set_thread_area(0x77a2a440)             = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: mprotect(0x779d2000, 4096, PROT_READ)   = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: mprotect(0x77a24000, 4096, PROT_READ)   = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: ioctl(0, TIOCNXCL, 0x7ffd3d18)          = -1 ENOTTY (Inappropriate ioctl for device)
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: ioctl(1, TIOCNXCL, 0x7ffd3d18)          = -1 ENOTTY (Inappropriate ioctl for device)
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: open("/dev/urandom", O_RDONLY)          = 3
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: read(3, ")o\225\220", 4)                = 4
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: close(3)                                = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: socket(PF_INET6, SOCK_DGRAM|SOCK_NONBLOCK, IPPROTO_IP) = 3
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: bind(3, {sa_family=AF_INET6, sin6_port=htons(27275), inet_pton(AF_INET6, "::", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: open("/dev/net/tun", O_RDWR|O_NONBLOCK) = 4
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: ioctl(4, TUNSETIFF, 0x7ffd3fd8)         = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: socket(PF_INET, SOCK_DGRAM, IPPROTO_UDP) = 5
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: ioctl(5, SIOCGIFMTU, {ifr_name="mmfd0", ifr_mtu=1500}) = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: ioctl(5, SIOCSIFMTU, {ifr_name="mmfd0", ifr_mtu=1280}) = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: close(5)                                = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: timerfd_create(CLOCK_MONOTONIC, 0x80 /_ TFD_??? */) = 5
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: timerfd_settime(5, 0, {it_interval={0, 0}, it_value={0, 1}}, NULL) = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: epoll_create(1)                         = 6
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: epoll_ctl(6, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLET, {u32=3, u64=12884901888}}) = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: epoll_ctl(6, EPOLL_CTL_ADD, 4, {EPOLLIN|EPOLLET, {u32=4, u64=17179869184}}) = 0
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: epoll_ctl(6, EPOLL_CTL_ADD, 0, {EPOLLIN, {u32=0, u64=0}}) = -1 EPERM (Operation not permitted)
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: write(2, "epoll_ctl", 9epoll_ctl)                = 9
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: write(2, "\n", 1
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: )                       = 1
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: exit_group(1)                           = ?
Thu Sep 22 07:34:07 2016 daemon.err strace[3539]: +++ exited with 1 +++

**Comment by mweinelt** [comment]
/etc/init.d/gluon-mmfd
```
#!/bin/sh /etc/rc.common

START=50

USE_PROCD=1
PROG=/usr/sbin/mmfd

start_service () {
procd_open_instance
procd_set_param stdout 1
procd_set_param stderr 1
procd_set_param command /usr/bin/strace "$PROG"
procd_close_instance
}
```

strace log
```
daemon.err strace[3539]: execve("/usr/sbin/mmfd", ["/usr/sbin/mmfd"], [/* 7 vars /]) = 0
daemon.err strace[3539]: mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|0x4000000, -1, 0) = 0x77a26000
daemon.err strace[3539]: stat("/etc/ld.so.cache", 0x7ffd3d80) = -1 ENOENT (No such file or directory)
daemon.err strace[3539]: open("/lib/libsetlbf.so", O_RDONLY) = 3
daemon.err strace[3539]: fstat(3, {st_mode=S_IFREG|0644, st_size=2184, ...}) = 0
daemon.err strace[3539]: mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|0x4000000, -1, 0) = 0x77a23000
daemon.err strace[3539]: read(3, "\177ELF\1\2\1\0\0\0\0\0\0\0\0\0\0\3\0\10\0\0\0\1\0\0\5@\0\0\0004"..., 4096) = 2184
daemon.err strace[3539]: mmap(NULL, 69632, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x779fd000
daemon.err strace[3539]: mmap(0x779fd000, 2084, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0x779fd000
daemon.err strace[3539]: mmap(0x77a0d000, 2184, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0x77a0d000
daemon.err strace[3539]: close(3) = 0
daemon.err strace[3539]: munmap(0x77a23000, 4096) = 0
daemon.err strace[3539]: open("/lib/libgcc_s.so.1", O_RDONLY) = 3
daemon.err strace[3539]: fstat(3, {st_mode=S_IFREG|0644, st_size=78648, ...}) = 0
daemon.err strace[3539]: mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|0x4000000, -1, 0) = 0x77a23000
daemon.err strace[3539]: read(3, "\177ELF\1\2\1\0\0\0\0\0\0\0\0\0\0\3\0\10\0\0\0\1\0\0006\340\0\0\0004"..., 4096) = 4096
daemon.err strace[3539]: mmap(NULL, 147456, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x779d9000
daemon.err strace[3539]: mmap(0x779d9000, 78268, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0x779d9000
daemon.err strace[3539]: mmap(0x779fc000, 824, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x13000) = 0x779fc000
daemon.err strace[3539]: close(3) = 0
daemon.err strace[3539]: munmap(0x77a23000, 4096) = 0
daemon.err strace[3539]: open("/lib/libc.so.0", O_RDONLY) = 3
daemon.err strace[3539]: fstat(3, {st_mode=S_IFREG|0755, st_size=359596, ...}) = 0
daemon.err strace[3539]: mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|0x4000000, -1, 0) = 0x77a23000
daemon.err strace[3539]: read(3, "\177ELF\1\2\1\0\0\0\0\0\0\0\0\0\0\3\0\10\0\0\0\1\0\0\235\0\0\0\0004"..., 4096) = 4096
daemon.err strace[3539]: mmap(NULL, 446464, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7796c000
daemon.err strace[3539]: mmap(0x7796c000, 352480, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0x7796c000
daemon.err strace[3539]: mmap(0x779d2000, 7340, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x56000) = 0x779d2000
daemon.err strace[3539]: mmap(0x779d4000, 17508, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x779d4000
daemon.err strace[3539]: close(3) = 0
daemon.err strace[3539]: munmap(0x77a23000, 4096) = 0
daemon.err strace[3539]: open("/lib/libgcc_s.so.1", O_RDONLY) = 3
daemon.err strace[3539]: fstat(3, {st_mode=S_IFREG|0644, st_size=78648, ...}) = 0
daemon.err strace[3539]: close(3) = 0
daemon.err strace[3539]: open("/lib/libc.so.0", O_RDONLY) = 3
daemon.err strace[3539]: fstat(3, {st_mode=S_IFREG|0755, st_size=359596, ...}) = 0
daemon.err strace[3539]: close(3) = 0
daemon.err strace[3539]: open("/lib/libc.so.0", O_RDONLY) = 3
daemon.err strace[3539]: fstat(3, {st_mode=S_IFREG|0755, st_size=359596, ...}) = 0
daemon.err strace[3539]: close(3) = 0
daemon.err strace[3539]: stat("/lib/ld-uClibc.so.0", {st_mode=S_IFREG|0755, st_size=28972, ...}) = 0
daemon.err strace[3539]: mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|0x4000000, -1, 0) = 0x77a23000
daemon.err strace[3539]: set_thread_area(0x77a2a440) = 0
daemon.err strace[3539]: mprotect(0x779d2000, 4096, PROT_READ) = 0
daemon.err strace[3539]: mprotect(0x77a24000, 4096, PROT_READ) = 0
daemon.err strace[3539]: ioctl(0, TIOCNXCL, 0x7ffd3d18) = -1 ENOTTY (Inappropriate ioctl for device)
daemon.err strace[3539]: ioctl(1, TIOCNXCL, 0x7ffd3d18) = -1 ENOTTY (Inappropriate ioctl for device)
daemon.err strace[3539]: open("/dev/urandom", O_RDONLY) = 3
daemon.err strace[3539]: read(3, ")o\225\220", 4) = 4
daemon.err strace[3539]: close(3) = 0
daemon.err strace[3539]: socket(PF_INET6, SOCK_DGRAM|SOCK_NONBLOCK, IPPROTO_IP) = 3
daemon.err strace[3539]: bind(3, {sa_family=AF_INET6, sin6_port=htons(27275), inet_pton(AF_INET6, "::", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = 0
daemon.err strace[3539]: open("/dev/net/tun", O_RDWR|O_NONBLOCK) = 4
daemon.err strace[3539]: ioctl(4, TUNSETIFF, 0x7ffd3fd8) = 0
daemon.err strace[3539]: socket(PF_INET, SOCK_DGRAM, IPPROTO_UDP) = 5
daemon.err strace[3539]: ioctl(5, SIOCGIFMTU, {ifr_name="mmfd0", ifr_mtu=1500}) = 0
daemon.err strace[3539]: ioctl(5, SIOCSIFMTU, {ifr_name="mmfd0", ifr_mtu=1280}) = 0
daemon.err strace[3539]: close(5) = 0
daemon.err strace[3539]: timerfd_create(CLOCK_MONOTONIC, 0x80 / TFD_??? */) = 5
daemon.err strace[3539]: timerfd_settime(5, 0, {it_interval={0, 0}, it_value={0, 1}}, NULL) = 0
daemon.err strace[3539]: epoll_create(1) = 6
daemon.err strace[3539]: epoll_ctl(6, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLET, {u32=3, u64=12884901888}}) = 0
daemon.err strace[3539]: epoll_ctl(6, EPOLL_CTL_ADD, 4, {EPOLLIN|EPOLLET, {u32=4, u64=17179869184}}) = 0
daemon.err strace[3539]: epoll_ctl(6, EPOLL_CTL_ADD, 0, {EPOLLIN, {u32=0, u64=0}}) = -1 EPERM (Operation not permitted)
daemon.err strace[3539]: write(2, "epoll_ctl", 9epoll_ctl) = 9
daemon.err strace[3539]: write(2, "\n", 1
daemon.err strace[3539]: ) = 1
daemon.err strace[3539]: exit_group(1) = ?
daemon.err strace[3539]: +++ exited with 1 +++
```

**Comment by mweinelt** [comment]
```
daemon.err strace[3539]: epoll_ctl(6, EPOLL_CTL_ADD, 0, {EPOLLIN, {u32=0, u64=0}}) = -1 EPERM (Operation not permitted)
```

Der dritte Parameter referenziert vmtl. STDIN und das gibt es im Environment von procd scheinbar nicht. Was soll auf STDIN überhaupt gelesen werden?

**Comment by christf** [comment]
In dem Beispiel lief der babelv vorher nicht. Ich hatte den per netifd mit folgendem script gestartet
https://github.com/freifunk-ffm/gluon/blob/n_babel-work/package/gluon-mesh-babel/files/lib/gluon/core/mesh/setup.d/babel-add-mesh-interface.sh

**Comment by christf** [comment]
Mit netifd - gleiches Bild.

**Comment by mweinelt** [comment]
Der connect zum babeld (https://github.com/tcatm/mmfd/blob/master/src/main.c#L283) erfolgt frühestens nachdem `epoll_ctl` auf dem `ctx->babelfd` (https://github.com/tcatm/mmfd/blob/master/src/main.c#L265) aufgerufen wird, der bis dahin eben noch `0` ist.

**Comment by christf** [comment]
ja, das ist korrekt. von einer interaktiven shell aus geht es. Wahrscheinlich weil da der mit 0 vorbelegte fd stdin ist...

**Comment by christf** [comment]
mit dem Patch von @lemoer geht es, daher schließe ich das issue.
